spring:
  application:
    name: laned-redis-example
    
  data:
    redis:
      host: localhost
      port: 6379
      connection:
        strategy: LANED  # CLASSIC | POOLED | LANED
        lanes: 8         # Number of multiplexed connections

logging:
  level:
    com.macstab.oss.redis.laned: INFO
    io.lettuce.core: WARN
    org.springframework.data.redis: INFO
